{"argument":"amount","code":"INVALID_ARGUMENT","level":"error","message":"value out-of-bounds (argument=\"amount\", value=\"115792089237316200000000000000000000000000000000000000000000000000000000000000000000\", code=INVALID_ARGUMENT, version=abi/5.7.0)","reason":"value out-of-bounds","service":"your-service-name","stack":"Error: value out-of-bounds (argument=\"amount\", value=\"115792089237316200000000000000000000000000000000000000000000000000000000000000000000\", code=INVALID_ARGUMENT, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Logger.throwArgumentError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:250:21)\n    at Coder._throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\abstract-coder.js:41:16)\n    at NumberCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\number.js:46:18)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:74:19\n    at Array.forEach (<anonymous>)\n    at pack (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:60:12)\n    at TupleCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:71:33)\n    at AbiCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:91:15)","timestamp":"2023-04-27T13:54:21.673Z","value":"115792089237316200000000000000000000000000000000000000000000000000000000000000000000"}
{"argument":"value","code":"INVALID_ARGUMENT","level":"error","message":"invalid BigNumber string (argument=\"value\", value=\"115792089237316195423570985008687907853269984665640564039457584007913129.639935\", code=INVALID_ARGUMENT, version=bignumber/5.7.0)","reason":"invalid BigNumber string","service":"your-service-name","stack":"Error: invalid BigNumber string (argument=\"value\", value=\"115792089237316195423570985008687907853269984665640564039457584007913129.639935\", code=INVALID_ARGUMENT, version=bignumber/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Logger.throwArgumentError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:250:21)\n    at BigNumber.from (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:199:27)\n    at NumberCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\number.js:36:39)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:74:19\n    at Array.forEach (<anonymous>)\n    at pack (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:60:12)\n    at TupleCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:71:33)\n    at AbiCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:91:15)","timestamp":"2023-04-27T14:11:56.424Z","value":"115792089237316195423570985008687907853269984665640564039457584007913129.639935"}
{"level":"error","message":"contract.decimals is not a function","service":"your-service-name","stack":"TypeError: contract.decimals is not a function\n    at initSupply (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/scripts/supply.js:13:37)\n    at supplyAsset (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/controllers/supplyController.js:12:45)\n    at Layer.handle [as handle_request] (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2023-05-01T08:05:50.975Z"}
{"address":"0x4DAFE12E1293D889221B1980672FE260Ac9dDd28","args":[],"code":"CALL_EXCEPTION","data":"0x","errorArgs":null,"errorName":null,"errorSignature":null,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","method":"decimals()","reason":null,"service":"your-service-name","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-01T08:11:25.471Z","transaction":{"data":"0x313ce567","to":"0x4DAFE12E1293D889221B1980672FE260Ac9dDd28"}}
{"level":"error","message":"proxyContractAddress is not defined","service":"your-service-name","stack":"ReferenceError: proxyContractAddress is not defined\n    at initSupply (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/scripts/supply.js:26:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async supplyAsset (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/controllers/supplyController.js:12:39)","timestamp":"2023-05-01T08:12:15.133Z"}
{"level":"error","message":"proxyContractAddress is not defined","service":"your-service-name","stack":"ReferenceError: proxyContractAddress is not defined\n    at initSupply (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/scripts/supply.js:26:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async supplyAsset (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/controllers/supplyController.js:12:39)","timestamp":"2023-05-01T08:13:17.987Z"}
{"level":"error","message":"proxyContractAddress is not defined","service":"your-service-name","stack":"ReferenceError: proxyContractAddress is not defined\n    at initSupply (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/scripts/supply.js:26:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async supplyAsset (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/controllers/supplyController.js:12:39)","timestamp":"2023-05-01T08:13:41.623Z"}
{"address":"0x4DAFE12E1293D889221B1980672FE260Ac9dDd28","args":[],"code":"CALL_EXCEPTION","data":"0x","errorArgs":null,"errorName":null,"errorSignature":null,"level":"error","message":"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)","method":"decimals()","reason":null,"service":"your-service-name","stack":"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-01T08:14:28.951Z","transaction":{"data":"0x313ce567","to":"0x4DAFE12E1293D889221B1980672FE260Ac9dDd28"}}
{"address":"0x2f5B9748001556E69C9248f1649FA71332d7FF31","args":["0x8da3FDf1835a00A65FDA4B5900adf0442be6745D","0xaf95Ff5fB592646D86BF240B3CaE0903b6E4dd38","10000000000000000000000"],"code":"CALL_EXCEPTION","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000","errorArgs":["No such asset supplied or invalid balance"],"errorName":"Error","errorSignature":"Error(string)","level":"error","message":"call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)","method":"canWithdrawExtraCollateral(address,address,uint256)","reason":"No such asset supplied or invalid balance","service":"your-service-name","stack":"Error: call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-01T08:16:36.539Z","transaction":{"data":"0x30faeb7b0000000000000000000000008da3fdf1835a00a65fda4b5900adf0442be6745d000000000000000000000000af95ff5fb592646d86bf240b3cae0903b6e4dd3800000000000000000000000000000000000000000000021e19e0c9bab2400000","to":"0x2f5B9748001556E69C9248f1649FA71332d7FF31"}}
{"address":"0x2f5B9748001556E69C9248f1649FA71332d7FF31","args":["0x8da3FDf1835a00A65FDA4B5900adf0442be6745D","0xaf95Ff5fB592646D86BF240B3CaE0903b6E4dd38","49911000000000000000000"],"code":"CALL_EXCEPTION","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000","errorArgs":["No such asset supplied or invalid balance"],"errorName":"Error","errorSignature":"Error(string)","level":"error","message":"call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)","method":"canWithdrawExtraCollateral(address,address,uint256)","reason":"No such asset supplied or invalid balance","service":"your-service-name","stack":"Error: call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-01T08:30:48.126Z","transaction":{"data":"0x30faeb7b0000000000000000000000008da3fdf1835a00a65fda4b5900adf0442be6745d000000000000000000000000af95ff5fb592646d86bf240b3cae0903b6e4dd38000000000000000000000000000000000000000000000a91ae446c30497c0000","to":"0x2f5B9748001556E69C9248f1649FA71332d7FF31"}}
